services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-annafinder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-annafinder}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-annafinder} -d ${POSTGRES_DB:-annafinder}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env.prod.example
    environment:
      APP_ENV: prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request, sys; import urllib.error; try: res = urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=5); except Exception: sys.exit(1); sys.exit(0 if res.status == 200 else 1)\""]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./.env.prod.example
    environment:
      APP_ENV: prod
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:3000/en/', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1));\""]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  pgdata:
    name: annafinder_pgdata
