name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to report a bug."
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see, and what did you expect?
      placeholder: "Describe the bug clearly."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: App version or git SHA
      placeholder: "e.g., 104be27 or v0.1.0"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs or screenshots (remove secrets).
      render: shell
    validations:
      required: false
