name: Bug report
description: Reportar um bug para ajudar a corrigir o produto
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Obrigado por reportar. Preencha os campos abaixo com o maximo de detalhes."
  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: OS, navegador/app, versao, etc.
      placeholder: "Windows 11, Chrome 122, v1.2.3"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Passo a passo claro para reproduzir o bug
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/prints
      description: Cole logs relevantes ou anexe imagens
    validations:
      required: false
