name: Feature request
description: Sugerir uma nova funcionalidade
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Obrigado pela sugestao. Explique o problema e o valor da solucao."
  - type: textarea
    id: problem
    attributes:
      label: Problema ou oportunidade
      description: Qual problema voce quer resolver?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: O que voce gostaria de ver?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Outras abordagens ou workarounds
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Impacto
      description: Quem se beneficia e como?
    validations:
      required: false
